services:
  postgres:
    image: postgres:17
    container_name: essalud-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: essalud
      POSTGRES_USER: essalud
      POSTGRES_PASSWORD: essalud

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
