spring.datasource.url=jdbc:postgresql://localhost:5432/essalud
spring.datasource.username=essalud
spring.datasource.password=essalud
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
